/**
 * @file  stm32f4xx_hal_conf.h
 * @brief STM32F4xx HAL driver configuration file.
 *
 * This file is a stub — in a full project it would be generated by
 * STM32CubeMX.  Only the modules required by the nautilus demos
 * (GPIO, USART, RCC) are enabled here.
 */

#ifndef STM32F4xx_HAL_CONF_H
#define STM32F4xx_HAL_CONF_H

#include "main.h"

#define HAL_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED

#include "stm32f4xx_hal.h"

#endif /* STM32F4xx_HAL_CONF_H */
